### ISSUE TITLE
batch ready is not obvious to user

### ISSUE THREAD

**Issue by phoebexy** [StanfordHCI/bang#438]
The UI call to action to join the chatroom is not clear. The UI should more obviously alert the user to enter the chat room. Please make the enter chat button much bigger and make the text white instead of black.

**Comment by markwhiting** [comment]
Both?, perhaps also change the document title so that the tab text changes.

**Comment by xehu** [comment]
I think, in general, that the user flow isn't particularly clear here.
Currently, the flow looks something like this:
1. An information page, where the user is supposed to click the (unclear) call to action; 
2. The helperbot page with the attention checks;
3. Upon achieving the requisite number of people, they get directed to the real task.

But doesn't this flow suffer from the same problem as before? **Namely, when users are in the helperbot stage, they're stuck giving attention checks for hours, not knowing when the task will be filled or how long they have to go.** Moreover, this flow suffers from a worse problem: **since the call to action isn't clear (the page doesn't change when the number of users is hit, and we no longer have the text "waiting on X more users"), it is now harder than before to see how long you have to wait.**

**Comment by xehu** [comment]
Small fixes that could help with this:
1. Make the number of people you're waiting on ("**waiting on: 4 Turkers**") clear in the helperBot chatroom.
2. Turn the first page call to action into **"I understand, proceed to waitroom"**, so that they understand the structure and what they're going into.
3. **Make the check-ins more interesting**, like asking a set of questions from a repertoire of brain teasers.

**Comment by markwhiting** [comment]
Also, we can explain to them why we need them to turn notifications on and then ask them if we can (as many apps do).

I'm also ok considering alternative flows here. Like having a few steps of buy in, before being put in a waiting room. 

Luckily, our new experiment designs have pretty low waiting times so I think attrition there is much lower than it used to be.

**Comment by phoebexy** [comment]
@deliveryweb it sounds like @xehu, @markwhiting and I are recommending a few UI additions:
- Make join chat button much bigger and more visible
- Turn the first-page join chat button text into: "I understand, proceed to waitroom"
- Change the wait room check-in question set into something more interesting
@markwhiting my recommendation for this last point would be to take random 10 line snippets of prior chat room conversations and ask the user which participant they like more.

**Comment by xehu** [comment]
Agree with @phoebexy on recommended action items here.

**Comment by dtatarenkov** [comment]
in dev
