### ISSUE TITLE
single teams require numRounds >=6

### ISSUE THREAD

**Issue by xehu** [StanfordHCI/bang#441]
Currently, if I use a Single Team template, the required number of rounds must be >=6. Can we make this number more flexible, just as with Multi-team?

I would like to be able to run Single Team with 3 or 4 rounds instead.

**Comment by deliveryweb** [comment]
The >=6 number is required only if the 'reconvene worst round' option is selected according to https://github.com/StanfordHCI/bang/issues/427#issuecomment-528989661. If the toggle is off numRounds can be anything >=4. We can't change this for batches with reconvening of worst rounds, because it can't work with new manipulation structure. Is there a need to change something in your opinion? @xehu

**Comment by xehu** [comment]
OK -- @markwhiting or @i-gao, can you guys explain more on the logic behind these settings so that we can document this appropriately? This seems like it may be more of a design misunderstanding.

**Comment by markwhiting** [comment]
This was a requirement because we needed two rounds that were outside the experimental manipulation that could be used for a manipulation check. Since our experiment in this case was 2 pairs of 2 rounds, that meant a total of 6 were required. This is correct and by design. 

We don't currently have a way to design the 2 independent condition version of the experiment with fewer than 6 interactions, however, thats something we can talk about from a research perspective as we move forward.

**Comment by markwhiting** [comment]
I don't think there's an issue here, right? 

I'll let you close @xehu if you agree, or let us know if there's something else you're thinking about?

**Comment by xehu** [comment]
@markwhiting @deliveryweb I think that, given the most recent design, this requirement doesn't make sense to have, and we should remove it. so, this is still an open issue.

**Comment by markwhiting** [comment]
So I think a critical thing here is where does the manipulation check go if its not being done in this way? Would you rather its a comparison of a random pair of rounds (I think this is reasonable), or did you have something else in mind?

**Comment by dtatarenkov** [comment]
@xehu there is no restriction if we don't reconvene the worst round. The number of rounds in this case can be less than 6. If we reconvene the worst round, we get 4 experimental rounds, which cannot be used for manipulation check. We want to have 2 non-exp rounds on sinlge-team manipulation check, this leads us to this requirement. We can remove it, then the manipulation check for single-team batches with reconvened worst round will stop working
